// ============================================================
// lib/animations/presets.ts
// Bibliothèque de presets d'animations prêts à l'emploi
// ============================================================

import {
  AnimationPreset,
  AnimationCategory,
  AnimationParams,
} from '@/types/animations';

// ─────────────────────────────────────────────────────────────
// PRESETS — APPARITION (entrance)
// ─────────────────────────────────────────────────────────────

const ENTRANCE_PRESETS: AnimationPreset[] = [
  {
    id: 'fade-in',
    label: 'Fade In',
    description: 'Apparition en fondu',
    category: 'entrance',
    type: 'fadeIn',
    icon: '✨',
    tags: ['doux', 'basique', 'populaire'],
    params: {
      name: 'Fade In',
      category: 'entrance',
      type: 'fadeIn',
      trigger: 'onEnterView',
      duration: 0.7,
      delay: 0,
      repeatCount: 0,
      ease: 'power2.out',
      fromOpacity: 0,
      toOpacity: 1,
    },
  },
  {
    id: 'slide-up',
    label: 'Slide Up',
    description: 'Monte depuis le bas',
    category: 'entrance',
    type: 'slideUp',
    icon: '⬆️',
    tags: ['populaire', 'moderne'],
    params: {
      name: 'Slide Up',
      category: 'entrance',
      type: 'slideUp',
      trigger: 'onEnterView',
      duration: 0.7,
      delay: 0,
      repeatCount: 0,
      ease: 'power3.out',
      fromY: 50,
      fromOpacity: 0,
      toY: 0,
      toOpacity: 1,
    },
  },
  {
    id: 'slide-down',
    label: 'Slide Down',
    description: 'Descend depuis le haut',
    category: 'entrance',
    type: 'slideDown',
    icon: '⬇️',
    tags: ['moderne'],
    params: {
      name: 'Slide Down',
      category: 'entrance',
      type: 'slideDown',
      trigger: 'onEnterView',
      duration: 0.7,
      delay: 0,
      repeatCount: 0,
      ease: 'power3.out',
      fromY: -50,
      fromOpacity: 0,
      toY: 0,
      toOpacity: 1,
    },
  },
  {
    id: 'slide-left',
    label: 'Slide Left',
    description: 'Arrive de la droite',
    category: 'entrance',
    type: 'slideLeft',
    icon: '⬅️',
    tags: ['moderne'],
    params: {
      name: 'Slide Left',
      category: 'entrance',
      type: 'slideLeft',
      trigger: 'onEnterView',
      duration: 0.7,
      delay: 0,
      repeatCount: 0,
      ease: 'power3.out',
      fromX: 60,
      fromOpacity: 0,
      toX: 0,
      toOpacity: 1,
    },
  },
  {
    id: 'slide-right',
    label: 'Slide Right',
    description: 'Arrive de la gauche',
    category: 'entrance',
    type: 'slideRight',
    icon: '➡️',
    tags: ['moderne'],
    params: {
      name: 'Slide Right',
      category: 'entrance',
      type: 'slideRight',
      trigger: 'onEnterView',
      duration: 0.7,
      delay: 0,
      repeatCount: 0,
      ease: 'power3.out',
      fromX: -60,
      fromOpacity: 0,
      toX: 0,
      toOpacity: 1,
    },
  },
  {
    id: 'zoom-in',
    label: 'Zoom In',
    description: 'Grandit en apparaissant',
    category: 'entrance',
    type: 'zoomIn',
    icon: '🔍',
    tags: ['impactant', 'moderne'],
    params: {
      name: 'Zoom In',
      category: 'entrance',
      type: 'zoomIn',
      trigger: 'onEnterView',
      duration: 0.6,
      delay: 0,
      repeatCount: 0,
      ease: 'back.out',
      fromScale: 0.7,
      fromOpacity: 0,
      toScale: 1,
      toOpacity: 1,
    },
  },
  {
    id: 'zoom-out',
    label: 'Zoom Out',
    description: 'Rétrécit en apparaissant',
    category: 'entrance',
    type: 'zoomOut',
    icon: '🔎',
    tags: ['original'],
    params: {
      name: 'Zoom Out',
      category: 'entrance',
      type: 'zoomOut',
      trigger: 'onEnterView',
      duration: 0.6,
      delay: 0,
      repeatCount: 0,
      ease: 'power2.out',
      fromScale: 1.3,
      fromOpacity: 0,
      toScale: 1,
      toOpacity: 1,
    },
  },
  {
    id: 'blur-in',
    label: 'Blur In',
    description: 'Apparition depuis le flou',
    category: 'entrance',
    type: 'blurIn',
    icon: '🌫️',
    tags: ['premium', 'moderne', 'original'],
    params: {
      name: 'Blur In',
      category: 'entrance',
      type: 'blurIn',
      trigger: 'onEnterView',
      duration: 0.8,
      delay: 0,
      repeatCount: 0,
      ease: 'power2.out',
      fromBlur: 12,
      fromOpacity: 0,
      toBlur: 0,
      toOpacity: 1,
    },
  },
  {
    id: 'flip-x',
    label: 'Flip X',
    description: 'Rotation sur l\'axe horizontal',
    category: 'entrance',
    type: 'flipX',
    icon: '🔄',
    tags: ['impactant', '3d'],
    params: {
      name: 'Flip X',
      category: 'entrance',
      type: 'flipX',
      trigger: 'onEnterView',
      duration: 0.8,
      delay: 0,
      repeatCount: 0,
      ease: 'power3.out',
      fromRotation: -90,
      fromOpacity: 0,
      toRotation: 0,
      toOpacity: 1,
    },
  },
  {
    id: 'bounce-in',
    label: 'Bounce In',
    description: 'Apparition avec rebond',
    category: 'entrance',
    type: 'bounceIn',
    icon: '🏀',
    tags: ['fun', 'dynamique'],
    params: {
      name: 'Bounce In',
      category: 'entrance',
      type: 'bounceIn',
      trigger: 'onEnterView',
      duration: 0.9,
      delay: 0,
      repeatCount: 0,
      ease: 'bounce.out',
      fromY: -40,
      fromOpacity: 0,
      toY: 0,
      toOpacity: 1,
    },
  },
  {
    id: 'elastic-in',
    label: 'Elastic In',
    description: 'Apparition élastique',
    category: 'entrance',
    type: 'elasticIn',
    icon: '🎯',
    tags: ['fun', 'premium'],
    params: {
      name: 'Elastic In',
      category: 'entrance',
      type: 'elasticIn',
      trigger: 'onEnterView',
      duration: 1,
      delay: 0,
      repeatCount: 0,
      ease: 'elastic.out',
      fromScale: 0,
      fromOpacity: 0,
      toScale: 1,
      toOpacity: 1,
    },
  },
  {
    id: 'rotate-in',
    label: 'Rotate In',
    description: 'Apparition en rotation',
    category: 'entrance',
    type: 'rotateIn',
    icon: '🌀',
    tags: ['dynamique'],
    params: {
      name: 'Rotate In',
      category: 'entrance',
      type: 'rotateIn',
      trigger: 'onEnterView',
      duration: 0.7,
      delay: 0,
      repeatCount: 0,
      ease: 'back.out',
      fromRotation: -180,
      fromOpacity: 0,
      toRotation: 0,
      toOpacity: 1,
    },
  },
  {
    id: 'skew-in',
    label: 'Skew In',
    description: 'Apparition avec déformation',
    category: 'entrance',
    type: 'skewIn',
    icon: '↗️',
    tags: ['original', 'moderne'],
    params: {
      name: 'Skew In',
      category: 'entrance',
      type: 'skewIn',
      trigger: 'onEnterView',
      duration: 0.6,
      delay: 0,
      repeatCount: 0,
      ease: 'power3.out',
      fromSkewX: 20,
      fromOpacity: 0,
      toSkewX: 0,
      toOpacity: 1,
    },
  },
];

// ─────────────────────────────────────────────────────────────
// PRESETS — SCROLL
// ─────────────────────────────────────────────────────────────

const SCROLL_PRESETS: AnimationPreset[] = [
  {
    id: 'fade-on-scroll',
    label: 'Fade au scroll',
    description: 'Apparaît en défilant',
    category: 'scroll',
    type: 'fadeInOnScroll',
    icon: '📜',
    tags: ['populaire', 'doux'],
    params: {
      name: 'Fade au scroll',
      category: 'scroll',
      type: 'fadeInOnScroll',
      trigger: 'onScroll',
      duration: 0.8,
      delay: 0,
      repeatCount: 0,
      ease: 'power2.out',
      fromOpacity: 0,
      toOpacity: 1,
      scrollStart: 'top 85%',
      scrollEnd: 'top 30%',
      scrub: false,
    },
  },
  {
    id: 'slide-up-scroll',
    label: 'Slide Up au scroll',
    description: 'Monte en défilant',
    category: 'scroll',
    type: 'slideUpOnScroll',
    icon: '🚀',
    tags: ['populaire', 'moderne'],
    params: {
      name: 'Slide Up au scroll',
      category: 'scroll',
      type: 'slideUpOnScroll',
      trigger: 'onScroll',
      duration: 0.8,
      delay: 0,
      repeatCount: 0,
      ease: 'power3.out',
      fromY: 60,
      fromOpacity: 0,
      toY: 0,
      toOpacity: 1,
      scrollStart: 'top 85%',
      scrollEnd: 'top 30%',
      scrub: false,
    },
  },
  {
    id: 'parallax',
    label: 'Parallax',
    description: 'Défilement en profondeur',
    category: 'scroll',
    type: 'parallax',
    icon: '🌄',
    tags: ['premium', 'immersif'],
    params: {
      name: 'Parallax',
      category: 'scroll',
      type: 'parallax',
      trigger: 'onScroll',
      duration: 1,
      delay: 0,
      repeatCount: 0,
      ease: 'none',
      parallaxSpeed: -0.3,
      scrollStart: 'top bottom',
      scrollEnd: 'bottom top',
      scrub: true,
    },
  },
  {
    id: 'stagger-children',
    label: 'Stagger enfants',
    description: 'Apparition en cascade',
    category: 'scroll',
    type: 'stagger',
    icon: '🎠',
    tags: ['premium', 'liste', 'cascade'],
    params: {
      name: 'Stagger',
      category: 'scroll',
      type: 'stagger',
      trigger: 'onScroll',
      duration: 0.5,
      delay: 0,
      repeatCount: 0,
      ease: 'power2.out',
      fromY: 30,
      fromOpacity: 0,
      toY: 0,
      toOpacity: 1,
      staggerAmount: 0.12,
      staggerFrom: 'start',
      scrollStart: 'top 85%',
      scrub: false,
    },
  },
  {
    id: 'zoom-on-scroll',
    label: 'Zoom au scroll',
    description: 'Grandit en défilant',
    category: 'scroll',
    type: 'zoomInOnScroll',
    icon: '🔭',
    tags: ['impactant'],
    params: {
      name: 'Zoom au scroll',
      category: 'scroll',
      type: 'zoomInOnScroll',
      trigger: 'onScroll',
      duration: 0.8,
      delay: 0,
      repeatCount: 0,
      ease: 'power2.out',
      fromScale: 0.85,
      fromOpacity: 0,
      toScale: 1,
      toOpacity: 1,
      scrollStart: 'top 85%',
      scrub: false,
    },
  },
  {
    id: 'pin-section',
    label: 'Section épinglée',
    description: 'La section reste fixe pendant le scroll',
    category: 'scroll',
    type: 'pinSection',
    icon: '📌',
    tags: ['premium', 'immersif'],
    params: {
      name: 'Section épinglée',
      category: 'scroll',
      type: 'pinSection',
      trigger: 'onScroll',
      duration: 1,
      delay: 0,
      repeatCount: 0,
      ease: 'none',
      scrollStart: 'top top',
      scrollEnd: '+=500',
      scrub: true,
      pin: true,
      pinSpacing: true,
    },
  },
  {
    id: 'rotate-on-scroll',
    label: 'Rotation au scroll',
    description: 'Tourne en défilant',
    category: 'scroll',
    type: 'rotateOnScroll',
    icon: '💫',
    tags: ['original'],
    params: {
      name: 'Rotation au scroll',
      category: 'scroll',
      type: 'rotateOnScroll',
      trigger: 'onScroll',
      duration: 1,
      delay: 0,
      repeatCount: 0,
      ease: 'none',
      fromRotation: 0,
      toRotation: 360,
      scrollStart: 'top bottom',
      scrollEnd: 'bottom top',
      scrub: 1,
    },
  },
  {
    id: 'slide-left-scroll',
    label: 'Slide Left au scroll',
    description: 'Arrive de la droite en défilant',
    category: 'scroll',
    type: 'slideLeftOnScroll',
    icon: '◀️',
    tags: ['moderne'],
    params: {
      name: 'Slide Left au scroll',
      category: 'scroll',
      type: 'slideLeftOnScroll',
      trigger: 'onScroll',
      duration: 0.8,
      delay: 0,
      repeatCount: 0,
      ease: 'power3.out',
      fromX: 80,
      fromOpacity: 0,
      toX: 0,
      toOpacity: 1,
      scrollStart: 'top 85%',
      scrub: false,
    },
  },
];

// ─────────────────────────────────────────────────────────────
// PRESETS — HOVER
// ─────────────────────────────────────────────────────────────

const HOVER_PRESETS: AnimationPreset[] = [
  {
    id: 'hover-scale',
    label: 'Zoom survol',
    description: 'Grandit au survol',
    category: 'hover',
    type: 'hoverScale',
    icon: '🔍',
    tags: ['populaire', 'basique'],
    params: {
      name: 'Zoom survol',
      category: 'hover',
      type: 'hoverScale',
      trigger: 'onHover',
      duration: 0.25,
      delay: 0,
      repeatCount: 0,
      ease: 'power2.out',
      hoverScale: 1.05,
      hoverDuration: 0.25,
    },
  },
  {
    id: 'hover-glow',
    label: 'Lueur survol',
    description: 'Effet lumineux au survol',
    category: 'hover',
    type: 'hoverGlow',
    icon: '✨',
    tags: ['premium', 'moderne'],
    params: {
      name: 'Lueur survol',
      category: 'hover',
      type: 'hoverGlow',
      trigger: 'onHover',
      duration: 0.3,
      delay: 0,
      repeatCount: 0,
      ease: 'power2.out',
      hoverDuration: 0.3,
    },
  },
  {
    id: 'hover-tilt',
    label: 'Tilt survol',
    description: 'Inclinaison 3D au survol',
    category: 'hover',
    type: 'hoverTilt',
    icon: '↗️',
    tags: ['premium', '3d', 'original'],
    params: {
      name: 'Tilt survol',
      category: 'hover',
      type: 'hoverTilt',
      trigger: 'onHover',
      duration: 0.3,
      delay: 0,
      repeatCount: 0,
      ease: 'power2.out',
      hoverRotation: 5,
      hoverDuration: 0.3,
    },
  },
  {
    id: 'hover-pulse',
    label: 'Pulsation survol',
    description: 'Pulsation continue au survol',
    category: 'hover',
    type: 'hoverPulse',
    icon: '💓',
    tags: ['fun'],
    params: {
      name: 'Pulsation survol',
      category: 'hover',
      type: 'hoverPulse',
      trigger: 'onHover',
      duration: 0.5,
      delay: 0,
      repeatCount: -1,
      ease: 'power1.inOut',
      hoverScale: 1.06,
      yoyo: true,
      hoverDuration: 0.5,
    },
  },
  {
    id: 'hover-slide-up',
    label: 'Glissement survol',
    description: 'Monte légèrement au survol',
    category: 'hover',
    type: 'hoverSlideUp',
    icon: '⬆️',
    tags: ['moderne'],
    params: {
      name: 'Glissement survol',
      category: 'hover',
      type: 'hoverSlideUp',
      trigger: 'onHover',
      duration: 0.25,
      delay: 0,
      repeatCount: 0,
      ease: 'power2.out',
      hoverY: -6,
      hoverDuration: 0.25,
    },
  },
  {
    id: 'hover-shake',
    label: 'Secousse survol',
    description: 'Tremblement rapide au survol',
    category: 'hover',
    type: 'hoverShake',
    icon: '💥',
    tags: ['fun', 'attention'],
    params: {
      name: 'Secousse survol',
      category: 'hover',
      type: 'hoverShake',
      trigger: 'onHover',
      duration: 0.4,
      delay: 0,
      repeatCount: 0,
      ease: 'power1.inOut',
      hoverDuration: 0.4,
    },
  },
];

// ─────────────────────────────────────────────────────────────
// PRESETS — BOUCLE (loop)
// ─────────────────────────────────────────────────────────────

const LOOP_PRESETS: AnimationPreset[] = [
  {
    id: 'float',
    label: 'Flottement',
    description: 'Monte et descend en continu',
    category: 'loop',
    type: 'float',
    icon: '🎈',
    tags: ['doux', 'ambiant'],
    params: {
      name: 'Flottement',
      category: 'loop',
      type: 'float',
      trigger: 'onLoad',
      duration: 2.5,
      delay: 0,
      repeatCount: -1,
      ease: 'sine.inOut',
      fromY: 0,
      toY: -12,
      yoyo: true,
    },
  },
  {
    id: 'pulse',
    label: 'Pulsation',
    description: 'Grossit et rétrécit en continu',
    category: 'loop',
    type: 'pulse',
    icon: '💓',
    tags: ['attention'],
    params: {
      name: 'Pulsation',
      category: 'loop',
      type: 'pulse',
      trigger: 'onLoad',
      duration: 1.2,
      delay: 0,
      repeatCount: -1,
      ease: 'sine.inOut',
      fromScale: 1,
      toScale: 1.06,
      yoyo: true,
    },
  },
  {
    id: 'spin',
    label: 'Rotation continue',
    description: 'Tourne en permanence',
    category: 'loop',
    type: 'spin',
    icon: '🌀',
    tags: ['dynamique'],
    params: {
      name: 'Rotation continue',
      category: 'loop',
      type: 'spin',
      trigger: 'onLoad',
      duration: 3,
      delay: 0,
      repeatCount: -1,
      ease: 'none',
      fromRotation: 0,
      toRotation: 360,
    },
  },
  {
    id: 'swing',
    label: 'Balancement',
    description: 'Oscillation de gauche à droite',
    category: 'loop',
    type: 'swing',
    icon: '🎷',
    tags: ['fun', 'ambiant'],
    params: {
      name: 'Balancement',
      category: 'loop',
      type: 'swing',
      trigger: 'onLoad',
      duration: 2,
      delay: 0,
      repeatCount: -1,
      ease: 'sine.inOut',
      fromRotation: -5,
      toRotation: 5,
      yoyo: true,
    },
  },
  {
    id: 'blink',
    label: 'Clignotement',
    description: 'Clignote en continu',
    category: 'loop',
    type: 'blink',
    icon: '💡',
    tags: ['attention'],
    params: {
      name: 'Clignotement',
      category: 'loop',
      type: 'blink',
      trigger: 'onLoad',
      duration: 0.8,
      delay: 0,
      repeatCount: -1,
      ease: 'power1.inOut',
      fromOpacity: 1,
      toOpacity: 0.2,
      yoyo: true,
    },
  },
];

// ─────────────────────────────────────────────────────────────
// PRESETS — TRANSITIONS DE PAGE
// ─────────────────────────────────────────────────────────────

const TRANSITION_PRESETS: AnimationPreset[] = [
  {
    id: 'page-fade',
    label: 'Fondu',
    description: 'Transition en fondu simple',
    category: 'transition',
    type: 'fade',
    icon: '🌫️',
    tags: ['doux', 'universel'],
    params: {
      name: 'Fondu',
      category: 'transition',
      type: 'fade',
      trigger: 'manual',
      duration: 0.4,
      delay: 0,
      repeatCount: 0,
      ease: 'power2.inOut',
      pageTransitionType: 'fade',
      pageTransitionDuration: 0.4,
      pageTransitionEase: 'power2.inOut',
    },
  },
  {
    id: 'page-slide-left',
    label: 'Glissement gauche',
    description: 'La page suivante arrive de droite',
    category: 'transition',
    type: 'slideLeft',
    icon: '◀️',
    tags: ['dynamique'],
    params: {
      name: 'Glissement gauche',
      category: 'transition',
      type: 'slideLeft',
      trigger: 'manual',
      duration: 0.5,
      delay: 0,
      repeatCount: 0,
      ease: 'power3.inOut',
      pageTransitionType: 'slideLeft',
      pageTransitionDuration: 0.5,
      pageTransitionEase: 'power3.inOut',
    },
  },
  {
    id: 'page-reveal',
    label: 'Révélation',
    description: 'Un rideau révèle la page',
    category: 'transition',
    type: 'reveal',
    icon: '🎭',
    tags: ['premium', 'impactant'],
    params: {
      name: 'Révélation',
      category: 'transition',
      type: 'reveal',
      trigger: 'manual',
      duration: 0.7,
      delay: 0,
      repeatCount: 0,
      ease: 'power4.inOut',
      pageTransitionType: 'reveal',
      pageTransitionDuration: 0.7,
      pageTransitionEase: 'power4.inOut',
    },
  },
  {
    id: 'page-curtain',
    label: 'Rideau',
    description: 'Un rideau vertical couvre puis révèle',
    category: 'transition',
    type: 'curtainVertical',
    icon: '🎪',
    tags: ['premium', 'dramatique'],
    params: {
      name: 'Rideau',
      category: 'transition',
      type: 'curtainVertical',
      trigger: 'manual',
      duration: 0.8,
      delay: 0,
      repeatCount: 0,
      ease: 'power4.inOut',
      pageTransitionType: 'curtainVertical',
      pageTransitionDuration: 0.8,
      pageTransitionEase: 'power4.inOut',
    },
  },
  {
    id: 'page-zoom',
    label: 'Zoom',
    description: 'Zoom de transition entre les pages',
    category: 'transition',
    type: 'zoomIn',
    icon: '🔍',
    tags: ['impactant', 'moderne'],
    params: {
      name: 'Zoom',
      category: 'transition',
      type: 'zoomIn',
      trigger: 'manual',
      duration: 0.5,
      delay: 0,
      repeatCount: 0,
      ease: 'power3.inOut',
      pageTransitionType: 'zoomIn',
      pageTransitionDuration: 0.5,
      pageTransitionEase: 'power3.inOut',
    },
  },
];

// ─────────────────────────────────────────────────────────────
// INDEX COMPLET
// ─────────────────────────────────────────────────────────────

export const ALL_PRESETS: AnimationPreset[] = [
  ...ENTRANCE_PRESETS,
  ...SCROLL_PRESETS,
  ...HOVER_PRESETS,
  ...LOOP_PRESETS,
  ...TRANSITION_PRESETS,
];

export const PRESETS_BY_CATEGORY: Record<AnimationCategory, AnimationPreset[]> = {
  entrance: ENTRANCE_PRESETS,
  scroll: SCROLL_PRESETS,
  hover: HOVER_PRESETS,
  click: [],
  loop: LOOP_PRESETS,
  exit: [],
  transition: TRANSITION_PRESETS,
};

export function getPresetById(id: string): AnimationPreset | undefined {
  return ALL_PRESETS.find(p => p.id === id);
}

export function getPresetsByCategory(category: AnimationCategory): AnimationPreset[] {
  return PRESETS_BY_CATEGORY[category] ?? [];
}

export function searchPresets(query: string): AnimationPreset[] {
  const q = query.toLowerCase();
  return ALL_PRESETS.filter(
    p =>
      p.label.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.tags.some(t => t.includes(q))
  );
}

/** Crée un AnimationParams à partir d'un preset */
export function instantiatePreset(preset: AnimationPreset): AnimationParams {
  return {
    ...preset.params,
    id: `anim-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    enabled: true,
  };
}

export const CATEGORY_LABELS: Record<AnimationCategory, string> = {
  entrance: 'Apparition',
  scroll: 'Scroll',
  hover: 'Survol',
  click: 'Clic',
  loop: 'Boucle',
  exit: 'Disparition',
  transition: 'Transition page',
};

export const CATEGORY_ICONS: Record<AnimationCategory, string> = {
  entrance: '✨',
  scroll: '📜',
  hover: '🖱️',
  click: '👆',
  loop: '🔁',
  exit: '👋',
  transition: '🎭',
};